name: genodesic
channels:
  - nvidia          # for pytorch-cuda metapackage
  - pytorch
  - conda-forge
dependencies:
  - python=3.10           # broadest binary support
  - pytorch=2.2.*         # includes torchvision / torchaudio wheels
  - pytorch-cuda=11.8     # pulls the full CUDA-11.8 runtime ✔ :contentReference[oaicite:0]{index=0}
  - jupyterlab
  - ipykernel


  - h5py
  - matplotlib
  - numpy
  - pandas
  - scanpy
  
  

