name: genodesic
channels:
  - rapidsai
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.2.*
  - pytorch-cuda=12.1
  - cuml=24.04.*
  - jupyterlab
  - ipykernel
  - h5py
  - matplotlib
  - numpy
  - pandas
  - scanpy
  - k3d
  - conda-build