# Configuration for a training run
model_type: "vpsde" # Options: "vpsde", "cfm", "rqnsf"

# Shared parameters
dim: 24
batch_size: 512
num_epochs: 50
learning_rate: 0.0001
validation_split: 0.2

# Model-specific hyperparameters
model_params:
  otcfm:
    hidden_dim: 2048
    activation: "selu"
    num_layers: 4
    batch_size: 700
  vpsde:
    hidden_dim: 2048
    num_layers: 6
    beta_min: 0.0001
    beta_max: 20
    activation: "selu"
  rqnsf:
    n_blocks: 3
    bins: 15
    subnet_width: 512
    subnet_activation: "selu"
